[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo

; Conexión a la base de datos
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = techstore_db

; Seguridad
admin_passwd = admin_techstore_2024

; Logging — sin logfile para que los logs aparezcan en docker logs
log_level = info

; Modo desarrollo (sin workers multiproceso)
workers = 0
